name: Nuget preview

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --configuration Release --output ./nupkgs

    # Push to GitHub Packages
    - name: Push to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/joren-vangoethem/index.json" --api-key "${{ secrets.GH_PAT_NUGET_PUSH }}" --skip-duplicate 
      
      # Push to nuget.org
    - name: Push to nuget.org
      run: dotnet nuget push ./nupkgs/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
